# The path for store your images, better be an absolute path
img_dir: /home/yuanguozheng/temp

# Example 127.0.0.1
bind_hostname: 0.0.0.0

# Port for running image resolve process
resolve_server_port: 18000

# Port for running image uploader process
uploader_server_port: 18001

# Your AccessToken for upload images, generate by yourself
access_token: '000'

# Whether or not print log
log_enable: true

# Enable Image Resolver Server
resolver_enable: true

# Enable Image Uploader Server
uploader_enable: true

# Available image extensions
available_image_extensions: ['.jpg', '.jpeg', '.png', '.gif']

# Path of watermark image
watermark_path: './watermark.png'

# Add watermark after upload an image automatically
add_watermark: true

# Whether or not generate webp/avif/heic format image
generate_compressed: true

# Formats for compressing
compressed_formats: ['.webp', '.avif', '.heic']

# The URL prefix of your image server for fetching image
image_server_url_prefix: 'http://localhost:18000/'

# Max upload image file size(MB)
max_image_size: 50

# File path for store pid, useful for Systemd, only support Linux
pid_file: /tmp/coderyuan-image-server.pid